import COLORS from "./color";
export const categoriesData = [
  {
    id: 1,
    name: "Education",
    icon: "fast-food",
    color: COLORS.GREEN,
    history: [
      {
        id: 1,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
      {
        id: 2,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Spending",
      },
      {
        id: 3,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Spending",
      },
      {
        id: 4,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Spending",
      },
      {
        id: 5,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
      {
        id: 6,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
      {
        id: 7,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
      {
        id: 8,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Spending",
      },
    ],
  },
  {
    id: 2,
    name: "Nutrition",
    icon: "fast-food",
    color: COLORS.BLACK,
    history: [],
  },
  {
    id: 3,
    name: "Child",
    icon: "fast-food",
    color: COLORS.DELETEBUTTONRED,
    history: [
      {
        id: 2,
        title: "Pampers",
        date: "20 July 2022",
        total: -100.0,
        type: "Spending",
      },
      {
        id: 2,
        title: "Pampers",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
    ],
  },
  {
    id: 4,
    name: "Beauty klqsdfjlkqsdf",
    icon: "fast-food",
    color: COLORS.SECONDARY,
    history: [
      {
        id: 3,
        title: "Face Mask",
        date: "20 July 2022",
        total: 50.0,
        type: "Income",
      },
    ],
  },
  {
    id: 5,
    name: "Computer",
    icon: "fast-food",
    color: COLORS.THIRD,
    history: [
      {
        id: 4,
        title: "Sunscreen cream",
        date: "20 July 2022",
        total: 50.0,
        type: "Spending",
      },
    ],
  },
  {
    id: 6,
    name: "Coffee",
    icon: "fast-food",
    color: COLORS.FACEBOOK,
    history: [
      {
        id: 5,
        title: "Face Mask",
        date: "20 July 2022",
        total: -50.0,
        type: "Spending",
      },
    ],
  },
  {
    id: 7,
    name: "Educati",
    icon: "fast-food",
    color: COLORS.GREEN,
    history: [
      {
        id: 1,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
      {
        id: 2,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Spending",
      },
      {
        id: 3,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Spending",
      },
      {
        id: 4,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Spending",
      },
      {
        id: 5,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
      {
        id: 6,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
      {
        id: 7,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Income",
      },
      {
        id: 8,
        title: "Tuition Fee",
        date: "20 July 2022",
        total: 100.0,
        type: "Spending",
      },
    ],
  },
  {
    id: 8,
    name: "Beaut",
    icon: "fast-food",
    color: COLORS.THIRD,
    history: [
      {
        id: 4,
        title: "Sunscreen cream",
        date: "20 July 2022",
        total: 50.0,
        type: "Spending",
      },
    ],
  },
  {
    id: 9,
    name: "Beauty",
    icon: "fast-food",
    color: COLORS.THIRD,
    history: [
      {
        id: 4,
        title: "Sunscreen cream",
        date: "20 July 2022",
        total: 50.0,
        type: "Spending",
      },
    ],
  },
  {
    id: 10,
    name: "Beauty & C",
    icon: "fast-food",
    color: COLORS.DELETEBUTTONRED,
    history: [
      {
        id: 4,
        title: "Sunscreen cream",
        date: "20 July 2022",
        total: 50.0,
        type: "Spending",
      },
    ],
  },
  {
    id: 11,
    name: "Beauty & Ca",
    icon: "fast-food",
    color: COLORS.TOTALINCOMES,
    history: [
      {
        id: 4,
        title: "Sunscreen cream",
        date: "20 July 2022",
        total: 50.0,
        type: "Spending",
      },
    ],
  },
  {
    id: 12,
    name: "Beauty & Car",
    icon: "fast-food",
    color: COLORS.TOTALSPENDINGS,
    history: [
      {
        id: 4,
        title: "Sunscreen cream",
        date: "20 July 2022",
        total: 50.0,
        type: "Spending",
      },
    ],
  },
];
