const COLORS = {
  BLACK: "#000",
  LIGHT: "#a5a5a5",
  WHITE: "#fff",
  PRIMARY: "#8687FD",
  SECONDARY: "#FFE7A1",
  THIRD: "#D6D6D6",
  GOOGLE: "#DC4E41",
  FACEBOOK: "#3A5896",
  GREY: "#AFAFAF",
  FOCUSEDTAB: "#3D40FE",
  DELETEBUTTONRED: "#FFA1A1",
  TOTALINCOMES: "#8FFF5A",
  TOTALSPENDINGS: "#F01",
  GREEN: "#0F0",
  RED: "#F00",
  BOTTOMBAR: "#F0F0F0",
  LIGHTGREY: "#DBDBDB",
  ORANGE: "#ED8E00",
  MEDUIMGREY: "#BFC3B1",
};

export default COLORS;
